# Emoji to join the lobby
JOIN_EMOJI = "✋"

# How long to keep the lobby open for reactions (in seconds)
LOBBY_SECONDS = 5

# Max seconds to wait for all players to submit their one-word hint each round
ROUND_HINT_TIMEOUT = 120

# Max seconds to collect votes via DM
VOTE_TIMEOUT = 90

# List of available words to be sent
# WORDS = [
#     "Pizza",
#     "Hamburguesa",
#     "Sushi",
#     "Tacos",
#     "Empanada",
#     "Arepa",
#     "Paella",
#     "Lasagna",
#     "Spaghetti",
#     "Ravioles",
#     "Hot dog / Pancho",
#     "Shawarma",
#     "Kebab",
#     "Burrito",
#     "Enchilada",
#     "Chivito (uruguayo)",
#     "Milanesa",
#     "Choripán",
#     "Ceviche",
#     "Feijoada",
#     "Pollo al curry",
#     "Pad Thai",
#     "Ramen",
#     "Gyozas",
#     "Dim sum",
#     "Sopa de miso",
#     "Pho (sopa vietnamita)",
#     "Croissant",
#     "Baguette",
#     "Panqueque",
#     "Waffles",
#     "Torta de chocolate",
#     "Cheesecake",
#     "Helado",
#     "Flan",
#     "Churros",
#     "Alfajor",
#     "Brownie",
#     "Donut",
#     "Muffin",
#     "Sándwich club",
#     "Bagel",
#     "Falafel",
#     "Hummus",
#     "Ensalada César",
#     "Gazpacho",
#     "Curry de vegetales",
#     "Risotto",
#     "Tortilla de papas",
#     "Pabellón criollo (venezolano)",
# ]

WORDS = [
    "AdreN",
    "Ax1Le",
    "boltz",
    "Boombl4",
    "broky",
    "chopper",
    "chelo",
    "coldzera",
    "dev1ce",
    "Dosia",
    "dupreeh",
    "electroNic",
    "EliGE",
    "FalleN",
    "fer",
    "flamie",
    "fnx",
    "f0rest",
    "frozen",
    "GeT_RiGhT",
    "gla1ve",
    "Hiko",
    "HObbit",
    "JW",
    "jdm64",
    "KSCERATO",
    "kNgV-",
    "KRiMZ",
    "kennyS",
    "Magisk",
    "m0NESY",
    "NAF",
    "NiKo",
    "nitr0",
    "olofmeister",
    "Perfecto",
    "ropz",
    "s1mple",
    "sh1ro",
    "shox",
    "shroud",
    "Skadoodle",
    "Stewie2K",
    "syrsoN",
    "TACO",
    "tarik",
    "Twistzz",
    "Xyp9x",
    "yuurih",
    "ZywOo",
]
